---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  labels:
    app: fortune
    version: v1

spec:
  containers:
    - name: fortune-container
      image: chukmunnlee/fortune:v1
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
