---
# ConfigMaps hold plain-text environmental variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: nw-config
  labels:
    app: nwapp
data:
  # Internal DNS record for the service
  # DB_HOST: nwdb-svc.nw-ns.svc.cluster.local # FQDNS
  DB_HOST: nwdb-svc

---
# Deployments manage the replication and maintenance of pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwapp-deploy
  labels:
    app: nwapp

spec:
  replicas: 3
  selector:
    matchLabels:
      # Labels for the pods that this deployment is associated with
      app: nwapp-pod

  template:
    metadata:
      name: nwapp-pod
      labels:
        app: nwapp-pod
    spec:
      containers:
        - name: nwapp-container
          image: zechywong/nwserver-test:v2
          imagePullPolicy: IfNotPresent
          # Pull from a Secret defined elsewhere
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: nw-secrets
                  key: MYSQL_ROOT_PASSWORD
            # Injected and displayed in `main.js`
            - name: INSTANCE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: nw-config
          ports:
            - name: nwapp-port
              containerPort: 3000

---
# Services manage ingress for the application
apiVersion: v1
kind: Service
metadata:
  name: nwapp-svc
spec:
  type: LoadBalancer
  selector:
    # Labels for the pods that this service routes to
    app: nwapp-pod
  ports:
  - port: 80
    targetPort: nwapp-port
