apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nwdb-pvc
  labels:
    app: nwdb
  # Annotations add optional additional custom information
  # annotations:
    # volume.beta.kubernetes.io/storage-provisioner: dobs.csi.digitalocean.com

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # No need to specify storageClassName if using the default
  # storageClassName: do-block-storage