---
# Secrets can hold b64-encoded environmental variables
apiVersion: v1
kind: Secret
metadata:
  name: nw-secrets
  labels:
    app: nwdb
data:
  MYSQL_ROOT_PASSWORD: Y2hhbmdlaXQ=

---
# Deployments manage the replication and maintenance of pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nwdb-deploy
  labels:
    app: nwdb

spec:
  replicas: 1
  selector:
    matchLabels:
      # Labels for the pods that this deployment is associated with
      app: nwdb-pod

  template:
    metadata:
      name: nwdb-pod
      labels:
        app: nwdb-pod
    spec:
      volumes:
        # Volume from PVC
        - name: nwdb-vol
          persistentVolumeClaim:
            claimName: nwdb-pvc
        # Temporary directory unique to this pod -- Can be shared by containers in this pod
        - name: share-dir
          emptyDir: {}

      initContainers:
        - name: busybox
          image: busybox
          command:
            - /bin/sh
            - -c
            - 'test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z "$(ls -A /scrub)" || exit 1'
          volumeMounts:
            - name: nwdb-vol
              mountPath: /scrub
            - name: share-dir
              mountPath: /tmp/share

      containers:
        - name: nwdb-container
          image: zechywong/nwdb-test:v3
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: nw-secrets
          ports:
            - name: nwdb-port
              containerPort: 3306

          volumeMounts:
            - mountPath: /var/lib/mysql
              name: nwdb-vol

---
apiVersion: v1
kind: Service
metadata:
  name: nwdb-svc
spec:
  type: ClusterIP
  selector:
    app: nwdb-pod
  ports:
    - port: 3306
      targetPort: nwdb-port
